In [2]:
import pandas as pd
df = pd.read_csv('./complete_occupations.csv')

In [2]:
df.dropna(how='all', axis=1, inplace=True)

In [3]:
df.to_csv('reformatted_occupations.csv')

In [4]:
df = pd.read_csv('./occupation_clusters.csv')

In [24]:
df.loc[df['Cluster'] == 2]

     Unnamed: 0  occupation_id  ...    Category Cluster
0             0              1  ...  specialist       2
16           16             17  ...       other       2
20           20             21  ...  specialist       2
33           33             34  ...       other       2
36           36             37  ...  specialist       2
51           51             52  ...       other       2
55           55             56  ...  specialist       2
93           93             94  ...  specialist       2
111         111            112  ...  specialist       2
135         135            136  ...  specialist       2
152         152            153  ...   inspector       2
157         157            158  ...  specialist       2
170         170            171  ...       other       2
176         176            177  ...  specialist       2
194         194            195  ...  technician       2
202         202            203  ...  specialist       2
213         213            214  ...   inspector       2

[17 rows x 7 columns]

In [5]:
df = pd.read_csv('./gpttaxonomyupdated.csv')
df

,Skill_ID,Original Skill Statement,Breakdown Sequence Number,New Sub-Skill Statement,Assigned Taxonomy Location,Additional Notes/Comments,Highest Level Taxonony Cluster
0,1,Experience and knowledge of hydrogen fueling e...,1,Experience with hydrogen fueling equipment and...,2. Maintenance and Monitoring of Hydrogen Equi...,Applicable to overall system maintenance,2.0
1,1,Experience and knowledge of hydrogen fueling e...,2,Experience with on-site hydrogen generation,16. Hydrogen Production Processes,On-site generation of hydrogen for fueling,16.0
2,1,Experience and knowledge of hydrogen fueling e...,3,Experience with hydrogen compression,13. Hydrogen Compression and Storage,Compression as part of the fueling process,13.0
3,1,Experience and knowledge of hydrogen fueling e...,4,Experience with hydrogen cooling systems,10. Cooling Systems in Hydrogen Production Plants,Cooling involved in storage and dispensing,10.0
4,1,Experience and knowledge of hydrogen fueling e...,5,Experience with hydrogen storage,13. Hydrogen Compression and Storage,Storage solutions for fueling stations,13.0
...,...,...,...,...,...,...,...
656,204,"Appropriate selection, design and maintenance ...",1,Selection of compression systems to withstand ...,13.1.2 Compression Technologies,Focused on selecting compression systems for h...,NaN
657,204,"Appropriate selection, design and maintenance ...",2,Design of compression systems to operate under...,13.1.2 Compression Technologies,Focused on designing compression systems for h...,NaN
658,204,"Appropriate selection, design and maintenance ...",3,Selection of turbine systems suitable for hydr...,25.3.2 Flame Stability and Burner Design,Focused on selecting turbines compatible with ...,NaN
659,204,"Appropriate selection, design and maintenance ...",4,Maintenance of compression systems in hydrogen...,6.4.2 Operation and Maintenance,Focused on maintaining compression systems in ...,NaN
660,204,"Appropriate selection, design and maintenance ...",5,Maintenance of turbine systems to ensure relia...,25.4.1.1 Boiler and Turbine Adjustments,Focused on maintaining turbines for hydrogen a...,NaN

In [6]:
mask = df['Skill_ID'].isin({13, 71, 112})
df = df.loc[~mask]

In [7]:
df = df.rename(columns = {'Original Skill Statement': 'requirement', 'New Sub-Skill Statement': 'skill'})
df['old_skill_id'] = df['Skill_ID']

In [8]:
requirement_mapping = pd.read_csv('./DataMappingSkills.csv')
requirement_mapping

,Completed?,Skill_ID,requirement_id,requirement_clean
0,y,1,3,Experience and knowledge of hydrogen fueling e...
1,y,2,4,Knowledge of hydrogen technologies and value p...
2,y,3,6,Knowledge of key instrumentation and electrica...
3,y,4,434,"Materials, coatings and inhibitors to use and ..."
4,y,5,19,"Knowledge and selection of type of materials, ..."
...,...,...,...,...
195,y,200,463,Well design and material choices based on unde...
196,y,201,464,Knowledge of key instrumentation and electrica...
197,y,202,465,Knowledge of key instrumentation and electrica...
198,y,203,466,Knowledge of hydrogen technologies and value p...
199,y,204,467,"Appropriate selection, design and maintenance ..."

In [9]:
df =pd.merge(df, requirement_mapping[['Skill_ID','requirement_id']], on='Skill_ID')

In [10]:
df = df.rename(columns={'Skill_ID': 'skill_id'})
df['skill_id'] = df.index + 1
df = df.drop(columns={'Breakdown Sequence Number'})

In [11]:
cols = df.columns.tolist()
cols = [cols[1]] + [cols[0]] + cols[2:]
cols = cols[-1:] + cols[:-1]
df = df[cols]

In [12]:
df.loc[df['skill'].str.contains(' CO2'), 'skill'] = df['skill'].str.replace(' CO2', ' carbon dioxide (CO2)', regex=False)

In [13]:
df.loc[df['skill'].str.contains(' CCS '), 'skill'] = df['skill'].str.replace(' CCS ', ' carbon capture and storage ')

In [14]:
df.loc[df['skill'].str.contains('CCS-related'), 'skill'] = df['skill'].str.replace('CCS-related', 'carbon capture and storage related')

In [15]:
df.loc[df['skill'].str.contains('ATR'), 'skill']

445    Maintenance of equipment in Autothermal Reform...
447    Understanding of Autothermal Reforming (ATR) p...
502    Selection of electrical and electronic equipme...
503    Maintenance of electrical and electronic syste...
518    Selection of key instrumentation for SMR and/o...
519    Maintenance of instrumentation systems in SMR ...
581    Understanding of hydrogen production process u...
584    Understanding of automated process systems for...
585    Knowledge of control systems for optimizing SM...
588    Understanding of control systems used in SMR/A...
589    Optimization of control systems in SMR/ATR hyd...
637    Knowledge of key instrumentation associated wi...
638    Knowledge of electrical equipment associated w...
639    Knowledge of systems used in SMR and ATR hydro...
Name: skill, dtype: object

In [19]:
df = df.drop(columns={'Assigned Taxonomy Location','Additional Notes/Comments','Highest Level Taxonony Cluster','old_skill_id'})

In [20]:
df.to_csv('./mnt/data/reformatted_skills.csv')

In [3]:
taxonomy_df = pd.read_csv('./mnt/data/complete_taxonomy.csv')

taxonomy_df.loc[taxonomy_df['Taxonomy ID'].str.contains(r'\.\s*$')]['Description']

0                      Understanding hydrogen properties
15      Maintenance and Monitoring of Hydrogen Equipment
38                   Hydrogen Storage and Transportation
57      Understanding hazardous areas involving hydrogen
73            Understanding Market Dynamics for Hydrogen
105                   High-Pressure Hydrogen Gas Systems
138                    Understanding Hydrogen Fuel Cells
161                Fuel Cell Maintenance and Replacement
177    Interpretation and Application of Technical Dr...
195        Cooling Systems in Hydrogen Production Plants
212    Hydrogen Production via Steam Methane Reformin...
235            Hydrogen Production via Coal Gasification
263                     Hydrogen Compression and Storage
285                    Hydrogen Liquefaction and Storage
307             Hydrogen Conversion to Chemical Carriers
327                        Hydrogen Production Processes
358                Gas Conversion and Interchangeability
378                  Hydrogen Interaction with Materials
407    Programming and Monitoring Control Systems in ...
443    Inspection and Maintenance of Hydrogen Fuel Ce...
475    High-Voltage Power Electronics in Hydrogen Pro...
498       Logistical Management of Hydrogen Supply Chain
530      Repurposing Hydrogen and Production By-Products
566            Integration of Hydrogen System Components
598    Operations and Processes in Co-Firing Power Pl...
626    Communication of Hydrogen's Role within the La...
Name: Description, dtype: object

In [32]:
import pandas as pd
df = pd.read_csv('./workforce_data_individual.csv')

In [33]:
df = df.sort_values(by=['Category'])
df.to_csv('workforce_data_individual.csv')